name: TempleCraft
author: Mike Singleton
main: com.msingleton.templecraft.TempleCraft
version: 0.11
commands:
  tc:
    description: Base command for TempleCraft
    usage: |
           /tc - List commands you have permission to use.
permissions:
    templecraft.*:
        description: Gives access to all TempleCraft commands
        children:
            templecraft.join: true            templecraft.leave: true            templecraft.ready: true            templecraft.templelist: true            templecraft.playerlist: true            templecraft.forcestart: true            templecraft.forceend: true
            templecraft.save: true
            templecraft.nullclass: true
            templecraft.enable: true
            templecraft.checkupdates: true
            templecraft.newtemple: true
            templecraft.deletetemple: true
            templecraft.edittemple: true
            templecraft.editall: true
            templecraft.savetemple: true
            templecraft.reload: true

    templecraft.editbasics:
        description: Gives access to basic edit commands
        children:
            templecraft.newtemple: true
            templecraft.edittemple: true
            templecraft.savetemple: true
            templecraft.addplayer: true
            templecraft.removeplayer: true

# General Play Commands
    templecraft.join:
        description: Join an open Temple.
        default: op
    templecraft.leave:
        description: Leave current temple.
        default: true
    templecraft.templelist:
        description: Lists all Temples.
        default: true
    templecraft.playerlist:
        description: Lists all players in a Temple.
        default: true
    templecraft.forcestart:
        description: Starts the Temple.
        default: op
    templecraft.forceend:
        description: Ends the Temple.
        default: op
# Account Commands
    templecraft.save:
        description: Saves the users class info.
        default: true
    templecraft.nullclass:
        description: Gives the user a null class.
        default: true

# Temple Edit Commands
    templecraft.checkupdates:
        description: Allows Checking for Updates.
        default: op
    templecraft.newtemple:
        description: Allows Creating New Temples.
        default: true
    templecraft.deletetemple:
        description: Allows Deletion of Temples.
        default: op
    templecraft.edittemple:
        description: Allows Editing Temples.
        default: true
    templecraft.addplayer:
        description: Allows Adding Players Access to Edit Temple.
        default: true
    templecraft.removeplayer:
        description: Allows Removing Players Access to Edit Temple.
        default: true
    templecraft.editall:
        description: Allows Editing & Adding/Removing of players in Any Temple.
        default: op
    templecraft.savetemple:
        description: Allows Saving the current Temple.
        default: true
    templecraft.reload:
        description: Allows Reloading TempleWorld.
        default: op